apiVersion: apps/v1
kind: Deployment
metadata:
  name: gps-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gps-service
  template:
    metadata:
      labels:
        app: gps-service
    spec:
      containers:
      - name: gps-service
        image: gps-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000